# --- Général ---
spring.application.name=BatimenTIGER
# Utilise le port fourni par le cloud, sinon 8090 par défaut
server.port=${PORT:8090}

# --- Base de données (Configuration Dynamique) ---
# Si DB_URL, DB_USER ou DB_PASSWORD sont définis sur Render, ils seront utilisés.
# Sinon, l'application utilisera vos réglages locaux (localhost) par défaut.
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/TIGER}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:user}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- OPTIMISATION : Gestion des fichiers volumineux ---
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# --- OPTIMISATION : Mémoire ---
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# --- Logs ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE